
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports data_rx]
set_property IOSTANDARD LVCMOS18 [get_ports error]
set_property IOSTANDARD LVCMOS18 [get_ports receive]
set_property IOSTANDARD LVCMOS18 [get_ports rst]
set_property IOSTANDARD LVCMOS18 [get_ports {data_out[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_out[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_out[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_out[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_out[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_out[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_out[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_out[0]}]

set_property PACKAGE_PIN AB19 [get_ports {data_out[3]}]
set_property PACKAGE_PIN AA19 [get_ports {data_out[4]}]
set_property PACKAGE_PIN Y20 [get_ports {data_out[1]}]
set_property PACKAGE_PIN Y19 [get_ports {data_out[5]}]
set_property PACKAGE_PIN Y18 [get_ports {data_out[7]}]
set_property PACKAGE_PIN Y21 [get_ports {data_out[0]}]
set_property PACKAGE_PIN AA18 [get_ports {data_out[6]}]
set_property PACKAGE_PIN AB20 [get_ports {data_out[2]}]
set_property PACKAGE_PIN AB21 [get_ports error]
set_property PACKAGE_PIN AA22 [get_ports receive]
set_property PACKAGE_PIN AB22 [get_ports rst]
set_property PACKAGE_PIN W17 [get_ports clk]
set_property PACKAGE_PIN W18 [get_ports data_rx]

create_clock -period 4.000 -name clk -waveform {0.000 2.000} [get_ports clk]
