create_clock -period 4.000 -name clk -waveform {0.000 2.000} [get_ports clk]

set_property IOSTANDARD LVCMOS18 [get_ports {data_in[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports data_tx]
set_property IOSTANDARD LVCMOS18 [get_ports rst]
set_property IOSTANDARD LVCMOS18 [get_ports send]
set_property IOSTANDARD LVCMOS18 [get_ports tx_done]
set_property IOSTANDARD LVCMOS18 [get_ports valid]

set_property PACKAGE_PIN U5 [get_ports {data_in[7]}]
set_property PACKAGE_PIN U6 [get_ports {data_in[6]}]
set_property PACKAGE_PIN U7 [get_ports {data_in[5]}]
set_property PACKAGE_PIN V7 [get_ports {data_in[4]}]
set_property PACKAGE_PIN W7 [get_ports {data_in[3]}]
set_property PACKAGE_PIN W6 [get_ports {data_in[2]}]
set_property PACKAGE_PIN W5 [get_ports {data_in[1]}]
set_property PACKAGE_PIN V4 [get_ports {data_in[0]}]
set_property PACKAGE_PIN T4 [get_ports data_tx]
set_property PACKAGE_PIN V5 [get_ports rst]
set_property PACKAGE_PIN T6 [get_ports send]
set_property PACKAGE_PIN R6 [get_ports tx_done]
set_property PACKAGE_PIN U4 [get_ports valid]


set_property PACKAGE_PIN AA9 [get_ports clk]
